[package]
name = "r2d2_redis"
version = "0.2.0"
authors = [
    "Steven Fackler <sfackler@gmail.com>",
    "Nev Delap <nevdelap@gmail.com>",
    "Simo Kinnunen <simo@shoqolate.com>",
]
license = "MIT"
description = "Redis support for the r2d2 connection pool"
repository = "https://github.com/sorccu/r2d2-redis"
documentation = "https://sorccu.github.io/r2d2-redis/doc/v0.2.0/r2d2_redis/"
keywords = ["redis", "pool", "database", "r2d2"]
include = ["src/**/*", "LICENSE", "Cargo.toml"]

[lib]
name = "r2d2_redis"
path = "src/lib.rs"
test = false

[[test]]
name = "test"
path = "tests/test.rs"

[dependencies]
r2d2 = "0.6"

[dependencies.redis]
version = "0.5"
git = "https://github.com/mitsuhiko/redis-rs"
rev = "3c960e0a9ff4241ac41595a67379d8ed91fa7a9f"
